# K-Nearest-Neighbors

Here is the implementation of the second collaborative model for recommending videos. The aim is to provide a new model to address cold-start issues for users. Indeed, when we have a new user that has not seen any video yet, we need to recommend videos with a little amount of data under our hands.

To address this issue, we are going to set a context setting: given that we are coding a recommender system for an app such as Tiktok or YouTube, even though the user has not seen any video, we already have data about the user from 2 sources:

- the platform requires or push the user to create an account with general data about himself/herself such as the age, the address, the country or about the gender. For instance, Netflix requires to have an account and Tiktok forces and push the user to create one.
- the application works with external partners to collect data about the user and get a "numerical footprint" that can be used to recommend videos. For instance, YouTube uses data collected from everywhere because it benefits from Google Ads and Google tracking features that knows the taste of the users. 

Given this setting, we can assume we have the minimal require amount of data to compute similarities between users to recommend videos. The KuaiRec dataset provides us encrypted features about users. We do not know what does they represent but we can make the assumptions that users can form groups by computing their similarities.

This leads us to use K-Nearest-Neighbors where we will compute similarities of our new user against all the existing ones in our database. Then we will recommend the most liked videos by the most similar users.

## Import libraries

In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import sys
sys.path.append('../')
import metrics

MANUAL_RANDOM_SEED=42
EMBEDDINGS_PATH='../embeddings'

## Load embeddings

In [2]:
user_ratings: pd.DataFrame = pd.read_pickle(f'{EMBEDDINGS_PATH}/users_ratings.pkl')
user_encrypted: pd.DataFrame = pd.read_pickle(f'{EMBEDDINGS_PATH}/users_encrypted.pkl')

In [3]:
# Set user_id as index to manipulate the dataframe better
user_ratings = user_ratings.set_index('user_id')

## Preprocess data

We need some preprocessing before using a custom KNN model. Let's use the first user to find out how to compute similarities in order to build the model.

In [4]:
# Get user encrypted features (this can be geographical location for instance, we do not know!)
user = user_encrypted.iloc[0]
user

onehot_feat0                    0
onehot_feat1                    1
onehot_feat2                   17
onehot_feat3                  638
onehot_feat4                  2.0
onehot_feat5                    0
onehot_feat6                    1
onehot_feat7                    6
onehot_feat8                  184
onehot_feat9                    6
onehot_feat10                   3
onehot_feat11                   0
onehot_feat12                 0.0
onehot_feat13                 0.0
onehot_feat14                 0.0
onehot_feat15                 0.0
onehot_feat16                 0.0
onehot_feat17                 0.0
user_active_degree    high_active
Name: 0, dtype: object

In [5]:
# Let's drop user_active_degree because we not need it to compute
# similarities between users, however we will need this feature later
user.drop('user_active_degree', axis=0).to_numpy().reshape(-1, 1)

array([[0],
       [1],
       [17],
       [638],
       [2.0],
       [0],
       [1],
       [6],
       [184],
       [6],
       [3],
       [0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0]], dtype=object)

In [6]:
# Compute similarities between our user and all others
user_similarities = cosine_similarity([user.drop('user_active_degree', axis=0).to_numpy()], user_encrypted.drop('user_active_degree', axis=1))
# We assume that we will get a 1 at then end of the array, because
# we compute the similarity of the user with itself
user_similarities.sort()
user_similarities

array([[0.27824314, 0.2807758 , 0.2811921 , ..., 0.99999238, 0.99999837,
        1.        ]])

## Implementing the KNN model

Here are the steps for implementing the model by hand:

1. Remove the user from the one I will compute the similarities on
2. Keep only the highest active users that is the one with the field `user_active_degree` is set on `high_active`. I am doing that because I want to recommend to new users videos that has been seen recently. It enables the predictions to follow the last trends on the platform without taking account of old users that might watched very old videos that do not match today tastes.
3. Compute similarities between the given user with all the others
4. Get the top users and get the video they liked
5. Recommend the videos that the most users liked that given 20 retrieved users, I will highly recommend a video that all the similar users liked.

For evaluating the model we just need a tiny adjustment: we want to recommend videos that the given user has already seen just for the purpose of having a comparison value to compute the metrics on.

In [7]:
# Implementation of the KNN recommender algorithm
def knn_recommend_videos(user_id: int, user_data: pd.DataFrame, users: pd.DataFrame, k: int = 5, validation: bool = False):
    users = users[users.index != user_id]
    # Keep highly active users
    users = users[users['user_active_degree'] == 'high_active']
    users = users.drop('user_active_degree', axis=1)

    # Compute similarities
    similarities = cosine_similarity([user_data], users).ravel()
    # Get top 20 users
    similarities = similarities.argsort()[::-1][:20]
    similar_users = users.iloc[similarities]

    # Retrieve their ratings
    similar_user_ratings = user_ratings.loc[similar_users.index]
    similar_user_ratings = similar_user_ratings.reset_index()

    if validation:
        # Filter by videos seen by the given user to evaluate the model
        similar_user_ratings = similar_user_ratings[similar_user_ratings['video_id'].isin(user_ratings.loc[user_id]['video_id'])]

    # Keep only the video that users liked
    similar_user_ratings = similar_user_ratings[similar_user_ratings['like'] == 1]

    # Get most common liked videos
    return similar_user_ratings['video_id'].value_counts().index[:k].to_list()

In [8]:
# Recommend video for our first user example above
knn_recommend_videos(0, user.drop('user_active_degree', axis=0).to_numpy(), user_encrypted, validation=True)

[10435, 9195, 4411, 4506, 7383]

## Evaluation

As this is an unsupervised model, we do not have any training phase so we can move on evaluating the actual knn model. I build the recommendations matrix that stores the video recommendations for each user and then apply the metrics on to measure the performance of the model.

In [9]:
recommendations = None

for user_id, user_data in user_encrypted.groupby('user_id'):
    print(f'Current user is: {user_id}')
    user_data = user_data.drop('user_active_degree', axis=1).to_numpy().ravel()
    recommendation = knn_recommend_videos(user_id, user_data, user_encrypted, k=20, validation=True)
    video_recommended = user_ratings.loc[user_id]
    video_recommended = video_recommended[video_recommended['video_id'].isin(recommendation)]

    if recommendations is None:
        recommendations = video_recommended
    else:
        recommendations = pd.concat([recommendations, video_recommended])

Current user is: 0
Current user is: 1
Current user is: 2
Current user is: 3
Current user is: 4
Current user is: 5
Current user is: 6
Current user is: 7
Current user is: 8
Current user is: 9
Current user is: 10
Current user is: 11
Current user is: 12
Current user is: 13
Current user is: 14
Current user is: 15
Current user is: 17
Current user is: 18
Current user is: 19
Current user is: 20
Current user is: 21
Current user is: 22
Current user is: 23
Current user is: 24
Current user is: 25
Current user is: 26
Current user is: 27
Current user is: 28
Current user is: 29
Current user is: 30
Current user is: 31
Current user is: 32
Current user is: 33
Current user is: 34
Current user is: 35
Current user is: 36
Current user is: 37
Current user is: 38
Current user is: 39
Current user is: 40
Current user is: 43
Current user is: 44
Current user is: 45
Current user is: 46
Current user is: 47
Current user is: 48
Current user is: 49
Current user is: 50
Current user is: 51
Current user is: 52
Current user is: 53
Current user is: 54
Current user is: 55
Current user is: 56
Current user is: 57
Current user is: 58
Current user is: 59
Current user is: 60
Current user is: 61
Current user is: 62
Current user is: 63
Current user is: 64
Current user is: 65
Current user is: 66
Current user is: 67
Current user is: 68
Current user is: 69
Current user is: 70
Current user is: 71
Current user is: 72
Current user is: 73
Current user is: 74
Current user is: 75
Current user is: 76
Current user is: 77
Current user is: 78
Current user is: 79
Current user is: 80
Current user is: 81
Current user is: 82
Current user is: 83
Current user is: 84
Current user is: 85
Current user is: 86
Current user is: 87
Current user is: 88
Current user is: 89
Current user is: 90
Current user is: 91
Current user is: 92
Current user is: 93
Current user is: 94
Current user is: 95
Current user is: 96
Current user is: 97
Current user is: 98
Current user is: 99
Current user is: 100
Current user is: 101
Current user is: 102
Current user is: 103
Current user is: 104
Current user is: 105
Current user is: 106
Current user is: 107
Current user is: 108
Current user is: 109
Current user is: 110
Current user is: 111
Current user is: 112
Current user is: 113
Current user is: 114
Current user is: 115
Current user is: 116
Current user is: 117
Current user is: 118
Current user is: 119
Current user is: 120
Current user is: 121
Current user is: 122
Current user is: 123
Current user is: 124
Current user is: 125
Current user is: 126
Current user is: 127
Current user is: 128
Current user is: 129
Current user is: 130
Current user is: 131
Current user is: 132
Current user is: 133
Current user is: 134
Current user is: 135
Current user is: 136
Current user is: 137
Current user is: 138
Current user is: 139
Current user is: 140
Current user is: 141
Current user is: 142
Current user is: 143
Current user is: 144
Current user is: 145
Current user is: 146
Current user is: 147
Current user is: 148
Current user is: 149
Current user is: 150
Current user is: 151
Current user is: 152
Current user is: 153
Current user is: 154
Current user is: 155
Current user is: 156
Current user is: 157
Current user is: 158
Current user is: 159
Current user is: 160
Current user is: 161
Current user is: 162
Current user is: 163
Current user is: 165
Current user is: 166
Current user is: 167
Current user is: 169
Current user is: 170
Current user is: 171
Current user is: 172
Current user is: 173
Current user is: 174
Current user is: 175
Current user is: 176
Current user is: 177
Current user is: 178
Current user is: 179
Current user is: 180
Current user is: 181
Current user is: 182
Current user is: 183
Current user is: 184
Current user is: 185
Current user is: 186
Current user is: 187
Current user is: 188
Current user is: 189
Current user is: 190
Current user is: 192
Current user is: 193
Current user is: 194
Current user is: 195
Current user is: 196
Current user is: 197
Current user is: 198
Current user is: 200
Current user is: 201
Current user is: 202
Current user is: 203
Current user is: 204
Current user is: 205
Current user is: 206
Current user is: 207
Current user is: 208
Current user is: 209
Current user is: 210
Current user is: 211
Current user is: 212
Current user is: 214
Current user is: 215
Current user is: 216
Current user is: 217
Current user is: 218
Current user is: 219
Current user is: 220
Current user is: 221
Current user is: 222
Current user is: 223
Current user is: 224
Current user is: 225
Current user is: 226
Current user is: 227
Current user is: 228
Current user is: 229
Current user is: 230
Current user is: 231
Current user is: 232
Current user is: 233
Current user is: 235
Current user is: 236
Current user is: 237
Current user is: 238
Current user is: 239
Current user is: 240
Current user is: 241
Current user is: 242
Current user is: 243
Current user is: 244
Current user is: 245
Current user is: 246
Current user is: 247
Current user is: 248
Current user is: 249
Current user is: 250
Current user is: 251
Current user is: 252
Current user is: 253
Current user is: 254
Current user is: 255
Current user is: 256
Current user is: 257
Current user is: 258
Current user is: 259
Current user is: 260
Current user is: 261
Current user is: 262
Current user is: 263
Current user is: 264
Current user is: 265
Current user is: 266
Current user is: 267
Current user is: 268
Current user is: 269
Current user is: 270
Current user is: 271
Current user is: 272
Current user is: 273
Current user is: 274
Current user is: 275
Current user is: 276
Current user is: 277
Current user is: 278
Current user is: 279
Current user is: 280
Current user is: 281
Current user is: 282
Current user is: 283
Current user is: 284
Current user is: 285
Current user is: 286
Current user is: 287
Current user is: 288
Current user is: 289
Current user is: 290
Current user is: 291
Current user is: 292
Current user is: 293
Current user is: 294
Current user is: 296
Current user is: 297
Current user is: 298
Current user is: 299
Current user is: 300
Current user is: 301
Current user is: 302
Current user is: 303
Current user is: 304
Current user is: 305
Current user is: 306
Current user is: 307
Current user is: 308
Current user is: 309
Current user is: 310
Current user is: 311
Current user is: 312
Current user is: 313
Current user is: 314
Current user is: 315
Current user is: 316
Current user is: 317
Current user is: 318
Current user is: 319
Current user is: 320
Current user is: 321
Current user is: 322
Current user is: 323
Current user is: 324
Current user is: 325
Current user is: 326
Current user is: 327
Current user is: 328
Current user is: 329
Current user is: 330
Current user is: 332
Current user is: 333
Current user is: 334
Current user is: 335
Current user is: 336
Current user is: 337
Current user is: 338
Current user is: 339
Current user is: 340
Current user is: 341
Current user is: 342
Current user is: 343
Current user is: 344
Current user is: 345
Current user is: 346
Current user is: 347
Current user is: 349
Current user is: 350
Current user is: 351
Current user is: 352
Current user is: 353
Current user is: 354
Current user is: 355
Current user is: 356
Current user is: 357
Current user is: 358
Current user is: 359
Current user is: 360
Current user is: 361
Current user is: 362
Current user is: 363
Current user is: 364
Current user is: 365
Current user is: 366
Current user is: 367
Current user is: 368
Current user is: 369
Current user is: 370
Current user is: 371
Current user is: 372
Current user is: 373
Current user is: 374
Current user is: 376
Current user is: 377
Current user is: 378
Current user is: 379
Current user is: 380
Current user is: 381
Current user is: 382
Current user is: 383
Current user is: 384
Current user is: 385
Current user is: 386
Current user is: 387
Current user is: 388
Current user is: 389
Current user is: 390
Current user is: 391
Current user is: 392
Current user is: 393
Current user is: 394
Current user is: 395
Current user is: 396
Current user is: 397
Current user is: 398
Current user is: 399
Current user is: 400
Current user is: 401
Current user is: 402
Current user is: 403
Current user is: 404
Current user is: 405
Current user is: 406
Current user is: 408
Current user is: 409
Current user is: 410
Current user is: 411
Current user is: 412
Current user is: 413
Current user is: 414
Current user is: 415
Current user is: 416
Current user is: 417
Current user is: 418
Current user is: 419
Current user is: 420
Current user is: 421
Current user is: 422
Current user is: 423
Current user is: 424
Current user is: 425
Current user is: 426
Current user is: 427
Current user is: 428
Current user is: 429
Current user is: 430
Current user is: 431
Current user is: 432
Current user is: 433
Current user is: 434
Current user is: 435
Current user is: 436
Current user is: 437
Current user is: 438
Current user is: 439
Current user is: 440
Current user is: 441
Current user is: 442
Current user is: 443
Current user is: 444
Current user is: 445
Current user is: 446
Current user is: 447
Current user is: 448
Current user is: 449
Current user is: 450
Current user is: 451
Current user is: 452
Current user is: 453
Current user is: 454
Current user is: 455
Current user is: 456
Current user is: 457
Current user is: 458
Current user is: 459
Current user is: 460
Current user is: 461
Current user is: 462
Current user is: 463
Current user is: 464
Current user is: 465
Current user is: 466
Current user is: 467
Current user is: 468
Current user is: 469
Current user is: 470
Current user is: 471
Current user is: 472
Current user is: 473
Current user is: 474
Current user is: 475
Current user is: 476
Current user is: 477
Current user is: 478
Current user is: 479
Current user is: 480
Current user is: 481
Current user is: 482
Current user is: 483
Current user is: 484
Current user is: 485
Current user is: 486
Current user is: 488
Current user is: 489
Current user is: 490
Current user is: 491
Current user is: 492
Current user is: 493
Current user is: 494
Current user is: 495
Current user is: 496
Current user is: 497
Current user is: 498
Current user is: 499
Current user is: 501
Current user is: 503
Current user is: 504
Current user is: 505
Current user is: 506
Current user is: 507
Current user is: 508
Current user is: 509
Current user is: 510
Current user is: 511
Current user is: 512
Current user is: 513
Current user is: 514
Current user is: 515
Current user is: 516
Current user is: 518
Current user is: 519
Current user is: 520
Current user is: 521
Current user is: 522
Current user is: 523
Current user is: 524
Current user is: 525
Current user is: 526
Current user is: 527
Current user is: 528
Current user is: 529
Current user is: 530
Current user is: 531
Current user is: 532
Current user is: 533
Current user is: 534
Current user is: 535
Current user is: 536
Current user is: 537
Current user is: 538
Current user is: 539
Current user is: 540
Current user is: 541
Current user is: 542
Current user is: 543
Current user is: 544
Current user is: 546
Current user is: 547
Current user is: 548
Current user is: 549
Current user is: 550
Current user is: 551
Current user is: 552
Current user is: 553
Current user is: 554
Current user is: 555
Current user is: 556
Current user is: 557
Current user is: 558
Current user is: 559
Current user is: 560
Current user is: 561
Current user is: 562
Current user is: 563
Current user is: 564
Current user is: 565
Current user is: 566
Current user is: 567
Current user is: 568
Current user is: 569
Current user is: 570
Current user is: 571
Current user is: 572
Current user is: 573
Current user is: 574
Current user is: 575
Current user is: 576
Current user is: 577
Current user is: 578
Current user is: 579
Current user is: 580
Current user is: 581
Current user is: 582
Current user is: 583
Current user is: 584
Current user is: 585
Current user is: 586
Current user is: 587
Current user is: 588
Current user is: 589
Current user is: 590
Current user is: 591
Current user is: 592
Current user is: 593
Current user is: 594
Current user is: 595
Current user is: 596
Current user is: 597
Current user is: 598
Current user is: 599
Current user is: 600
Current user is: 601
Current user is: 602
Current user is: 603
Current user is: 604
Current user is: 605
Current user is: 606
Current user is: 607
Current user is: 608
Current user is: 609
Current user is: 610
Current user is: 611
Current user is: 612
Current user is: 613
Current user is: 614
Current user is: 615
Current user is: 616
Current user is: 617
Current user is: 618
Current user is: 619
Current user is: 620
Current user is: 621
Current user is: 622
Current user is: 623
Current user is: 624
Current user is: 625
Current user is: 626
Current user is: 627
Current user is: 628
Current user is: 630
Current user is: 631
Current user is: 632
Current user is: 634
Current user is: 635
Current user is: 636
Current user is: 637
Current user is: 638
Current user is: 639
Current user is: 640
Current user is: 641
Current user is: 642
Current user is: 643
Current user is: 644
Current user is: 645
Current user is: 646
Current user is: 647
Current user is: 648
Current user is: 649
Current user is: 650
Current user is: 651
Current user is: 652
Current user is: 653
Current user is: 654
Current user is: 655
Current user is: 656
Current user is: 657
Current user is: 658
Current user is: 659
Current user is: 660
Current user is: 661
Current user is: 662
Current user is: 663
Current user is: 664
Current user is: 665
Current user is: 666
Current user is: 667
Current user is: 668
Current user is: 669
Current user is: 670
Current user is: 671
Current user is: 672
Current user is: 673
Current user is: 674
Current user is: 675
Current user is: 676
Current user is: 677
Current user is: 678
Current user is: 679
Current user is: 680
Current user is: 681
Current user is: 682
Current user is: 683
Current user is: 684
Current user is: 686
Current user is: 687
Current user is: 688
Current user is: 689
Current user is: 690
Current user is: 691
Current user is: 692
Current user is: 693
Current user is: 694
Current user is: 695
Current user is: 696
Current user is: 697
Current user is: 698
Current user is: 699
Current user is: 700
Current user is: 701
Current user is: 702
Current user is: 703
Current user is: 704
Current user is: 705
Current user is: 706
Current user is: 707
Current user is: 708
Current user is: 709
Current user is: 710
Current user is: 711
Current user is: 712
Current user is: 713
Current user is: 714
Current user is: 715
Current user is: 716
Current user is: 717
Current user is: 718
Current user is: 719
Current user is: 720
Current user is: 721
Current user is: 722
Current user is: 723
Current user is: 724
Current user is: 725
Current user is: 726
Current user is: 727
Current user is: 728
Current user is: 729
Current user is: 730
Current user is: 731
Current user is: 732
Current user is: 733
Current user is: 734
Current user is: 735
Current user is: 736
Current user is: 737
Current user is: 738
Current user is: 739
Current user is: 740
Current user is: 741
Current user is: 742
Current user is: 743
Current user is: 744
Current user is: 745
Current user is: 746
Current user is: 747
Current user is: 748
Current user is: 749
Current user is: 750
Current user is: 751
Current user is: 752
Current user is: 753
Current user is: 754
Current user is: 755
Current user is: 756
Current user is: 757
Current user is: 758
Current user is: 759
Current user is: 760
Current user is: 761
Current user is: 762
Current user is: 763
Current user is: 764
Current user is: 765
Current user is: 766
Current user is: 767
Current user is: 768
Current user is: 769
Current user is: 770
Current user is: 771
Current user is: 772
Current user is: 773
Current user is: 774
Current user is: 775
Current user is: 776
Current user is: 777
Current user is: 778
Current user is: 779
Current user is: 780
Current user is: 781
Current user is: 782
Current user is: 783
Current user is: 784
Current user is: 785
Current user is: 786
Current user is: 787
Current user is: 788
Current user is: 789
Current user is: 790
Current user is: 791
Current user is: 792
Current user is: 793
Current user is: 794
Current user is: 795
Current user is: 796
Current user is: 797
Current user is: 798
Current user is: 799
Current user is: 800
Current user is: 801
Current user is: 802
Current user is: 803
Current user is: 804
Current user is: 805
Current user is: 806
Current user is: 807
Current user is: 808
Current user is: 809
Current user is: 810
Current user is: 811
Current user is: 812
Current user is: 814
Current user is: 815
Current user is: 816
Current user is: 817
Current user is: 818
Current user is: 819
Current user is: 820
Current user is: 821
Current user is: 822
Current user is: 823
Current user is: 824
Current user is: 825
Current user is: 826
Current user is: 827
Current user is: 828
Current user is: 829
Current user is: 830
Current user is: 831
Current user is: 832
Current user is: 833
Current user is: 834
Current user is: 835
Current user is: 836
Current user is: 837
Current user is: 838
Current user is: 839
Current user is: 840
Current user is: 841
Current user is: 842
Current user is: 843
Current user is: 844
Current user is: 845
Current user is: 846
Current user is: 848
Current user is: 849
Current user is: 850
Current user is: 851
Current user is: 852
Current user is: 853
Current user is: 854
Current user is: 855
Current user is: 856
Current user is: 857
Current user is: 858
Current user is: 859
Current user is: 860
Current user is: 861
Current user is: 862
Current user is: 863
Current user is: 864
Current user is: 865
Current user is: 866
Current user is: 867
Current user is: 868
Current user is: 869
Current user is: 870
Current user is: 871
Current user is: 872
Current user is: 873
Current user is: 874
Current user is: 875
Current user is: 876
Current user is: 877
Current user is: 878
Current user is: 880
Current user is: 881
Current user is: 882
Current user is: 883
Current user is: 884
Current user is: 885
Current user is: 886
Current user is: 887
Current user is: 888
Current user is: 889
Current user is: 890
Current user is: 891
Current user is: 892
Current user is: 893
Current user is: 894
Current user is: 895
Current user is: 896
Current user is: 897
Current user is: 898
Current user is: 899
Current user is: 900
Current user is: 901
Current user is: 902
Current user is: 903
Current user is: 904
Current user is: 905
Current user is: 906
Current user is: 907
Current user is: 908
Current user is: 909
Current user is: 910
Current user is: 911
Current user is: 912
Current user is: 913
Current user is: 914
Current user is: 915
Current user is: 916
Current user is: 917
Current user is: 918
Current user is: 919
Current user is: 920
Current user is: 921
Current user is: 922
Current user is: 923
Current user is: 924
Current user is: 925
Current user is: 926
Current user is: 927
Current user is: 928
Current user is: 929
Current user is: 930
Current user is: 932
Current user is: 933
Current user is: 934
Current user is: 935
Current user is: 936
Current user is: 937
Current user is: 938
Current user is: 939
Current user is: 940
Current user is: 941
Current user is: 942
Current user is: 943
Current user is: 944
Current user is: 945
Current user is: 946
Current user is: 947
Current user is: 948
Current user is: 949
Current user is: 950
Current user is: 951
Current user is: 952
Current user is: 953
Current user is: 954
Current user is: 955
Current user is: 956
Current user is: 957
Current user is: 958
Current user is: 960
Current user is: 961
Current user is: 962
Current user is: 963
Current user is: 964
Current user is: 965
Current user is: 966
Current user is: 967
Current user is: 968
Current user is: 969
Current user is: 970
Current user is: 971
Current user is: 972
Current user is: 973
Current user is: 974
Current user is: 975
Current user is: 976
Current user is: 977
Current user is: 978
Current user is: 979
Current user is: 980
Current user is: 981
Current user is: 982
Current user is: 983

In [10]:
recommendations.head()

         video_id  like  watch_ratio
user_id
0            5853     1     2.587314
0            8435     1     3.525128
0           10021     1     1.477522
0            7383     1     4.318226
0            2629     0     0.144295

In [ ]:
# Select columns in the recommendation dataframe to compute the diversity metric on
video_content: pd.DataFrame = pd.read_pickle(f'{EMBEDDINGS_PATH}/videos_content.pkl')
video_tags: pd.DataFrame = pd.read_pickle(f'{EMBEDDINGS_PATH}/videos_one_hot_tags.pkl')

recommendations = recommendations.reset_index()
recommendations = recommendations.merge(video_tags, on='video_id')
recommendations = recommendations.merge(video_content.iloc[:, 2:], on='video_id')

recommendations.head()

,user_id,video_id,like,watch_ratio,tag_0,tag_1,tag_2,tag_3,tag_4,tag_5,...,tag_28,tag_29,tag_30,show_cnt,play_cnt,valid_play_cnt,like_cnt,comment_cnt,share_cnt,video_duration
0,0,5853,1,2.587314,0,0,0,0,0,0,...,1,0,0,809435,817112,460540,10079,95,11,5234
1,0,8435,1,3.525128,0,0,0,0,0,0,...,0,0,0,81061,84472,68445,466,0,0,3900
2,0,10021,1,1.477522,0,0,0,0,0,0,...,0,0,0,3095234,948298,388491,49343,3130,279,8475
3,0,7383,1,4.318226,0,0,0,0,0,0,...,0,0,0,384622,393672,310240,2078,12,3,3067
4,0,2629,0,0.144295,0,0,0,0,0,0,...,0,0,0,958437,887335,590171,75657,1582,39,5267

In [ ]:
# Select columns in the recommendation dataframe to compute the diversity metric on
video_content_columns = recommendations.columns[4:]
video_content_columns

Index(['tag_0', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7',
       'tag_8', 'tag_9', 'tag_10', 'tag_11', 'tag_12', 'tag_13', 'tag_14',
       'tag_15', 'tag_16', 'tag_17', 'tag_18', 'tag_19', 'tag_20', 'tag_21',
       'tag_22', 'tag_23', 'tag_24', 'tag_25', 'tag_26', 'tag_27', 'tag_28',
       'tag_29', 'tag_30', 'show_cnt', 'play_cnt', 'valid_play_cnt',
       'like_cnt', 'comment_cnt', 'share_cnt', 'video_duration'],
      dtype='object')

In [14]:
# Top videos to retrieve
kx = [5, 10, 15, 20]

for k in kx:
    # I use the metrics python script where I implemented all the relevant metrics
    # that I want to use. See metrics.py for more information
    precision = metrics.precision_at_k(recommendations, k)
    ndgc = metrics.ndcg_at_k(recommendations, k)
    diversity = metrics.inter_list_diversity_at_k(recommendations, video_content_columns, k)

    print(f'Precision@{k} -> {precision}')
    print(f'NDCG@{k} -> {ndgc}')
    print(f'ILD@{k} -> {diversity}')
    print()

Precision@5 -> 0.7058414262936658
NDCG@5 -> 0.8588479725319983
ILD@5 -> 0.9369053860677685

Precision@10 -> 0.6969415857370633
NDCG@10 -> 0.8647343765683367
ILD@10 -> 0.9395781555695202

Precision@15 -> 0.6926511088563561
NDCG@15 -> 0.86678049127918
ILD@15 -> 0.9395422756394614

Precision@20 -> 0.6931946658936078
NDCG@20 -> 0.8689730607383425
ILD@20 -> 0.9403994849321557

## Interpretations

As we can see, the model top up with Precision@5 at 70%. This is actual a very good result given that we have very limited knowledge about the user. This model will be actually very useful if the user is new that is for example if he/she did not like at least 5 or 10 videos. Furthermore, we can see that KNN is the model with the highest diversity metric so far compare to the other models I implemented showing that users tend to like videos that are not popular at first or they do not seem to like a certain category of video.

I will use the model in a certain context (so if the user is new to the recommender system) and then switch to stronger model when we collect enough data about the video taste of the user.